name: E2E Tests

on:
  pull_request:
    branches: [main]
    paths:
      - "app/**"
      - "tests/**"
      - "package.json"
      - "jest.e2e.config.mjs"
      - "jest-puppeteer.config.js"
      - "scripts/run-e2e-tests.js"
      - ".github/workflows/e2e-tests.yml"

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Install Chrome
        run: npx puppeteer browsers install chrome

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3-dev \
            libatk-bridge2.0-dev \
            libdrm-dev \
            libxkbcommon-dev \
            libxcomposite-dev \
            libxdamage-dev \
            libxrandr-dev \
            libgbm-dev \
            libxss-dev \
            libasound2-dev

      - name: Run E2E Tests
        run: pnpm test:e2e:ci
        env:
          CI: true
          HEADLESS: true
          NODE_ENV: test

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            tests/e2e/results/
            *.log
          retention-days: 7
